# Streamlit Secrets Configuration
# Copy this to .streamlit/secrets.toml and fill in your actual values

[general]
# OpenAI API Configuration
OPENAI_API_KEY = "sk-your-openai-api-key-here"
OPENAI_MODEL = "gpt-4o-mini"

# Application Settings
APP_NAME = "Agentic BI Platform"
DEBUG_MODE = false

# Database Configuration (if needed in future)
# DATABASE_URL = "your-database-url-here"

# Third-party Service Keys (if needed)
# GOOGLE_API_KEY = "your-google-api-key"
# AWS_ACCESS_KEY_ID = "your-aws-access-key"
# AWS_SECRET_ACCESS_KEY = "your-aws-secret-key"

# Email Configuration (for notifications, if needed)
# SMTP_SERVER = "smtp.gmail.com"
# SMTP_PORT = 587
# EMAIL_USER = "your-email@gmail.com"
# EMAIL_PASSWORD = "your-app-password"

# Analytics (if needed)
# GOOGLE_ANALYTICS_ID = "your-ga-id"

# Feature Flags
ENABLE_ADVANCED_FEATURES = true
ENABLE_CACHING = true
ENABLE_LOGGING = true